import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Card, Typography, Select, TimePicker, Button, Table, Popconfirm, Space, App, Spin, Tag,
} from 'antd';
import {
  FileTextOutlined, DeleteOutlined, ClockCircleOutlined, SaveOutlined, CheckCircleOutlined, EyeOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import api from '../../api/client';
import { DASH_CSS } from '../../components/DashboardStatCard.jsx';

const { Title, Text } = Typography;

const WEEKDAY_OPTIONS = [
  { value: 0, label: 'Sunday' }, { value: 1, label: 'Monday' }, { value: 2, label: 'Tuesday' },
  { value: 3, label: 'Wednesday' }, { value: 4, label: 'Thursday' }, { value: 5, label: 'Friday' },
  { value: 6, label: 'Saturday' },
];

// ── Automatic snapshot schedule — day + time weeklyReportScheduler.js reads
// on every reload. Saving takes effect immediately, no app restart needed.
function ScheduleCard() {
  const { message } = App.useApp();
  const [dayOfWeek, setDayOfWeek] = useState(3);
  const [time, setTime] = useState(dayjs('08:00', 'HH:mm'));
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    api.get('/weekly-report/schedule')
      .then(r => {
        setDayOfWeek(r.data.day_of_week ?? 3);
        const hh = String(r.data.hour ?? 8).padStart(2, '0');
        const mm = String(r.data.minute ?? 0).padStart(2, '0');
        setTime(dayjs(`${hh}:${mm}`, 'HH:mm'));
      })
      .catch(() => message.error('Failed to load snapshot schedule'))
      .finally(() => setLoading(false));
  }, []); // eslint-disable-line

  const save = async () => {
    setSaving(true);
    setSaved(false);
    try {
      await api.put('/weekly-report/schedule', {
        day_of_week: dayOfWeek,
        hour: time.hour(),
        minute: time.minute(),
      });
      message.success('Schedule saved — takes effect immediately.');
      setSaved(true);
    } catch (e) {
      message.error(e.response?.data?.error || 'Failed to save schedule');
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <div style={{ textAlign: 'center', padding: 40 }}><Spin /></div>;

  return (
    <Card className="dashcard" style={{ marginBottom: 20 }}>
      <Space style={{ marginBottom: 16 }}>
        <ClockCircleOutlined style={{ fontSize: 20, color: '#5a4fcf' }} />
        <Title level={5} style={{ margin: 0 }}>Automatic Snapshot Schedule</Title>
      </Space>
      <Text type="secondary" style={{ display: 'block', marginBottom: 16 }}>
        A snapshot is saved automatically at this day and time every week (also sends the Teams
        notification, if enabled under Admin → Teams Notifications). "Generate Now" on the Weekly
        Report page runs independently of this schedule.
      </Text>
      <Space size={16} wrap>
        <div>
          <Text strong style={{ display: 'block', marginBottom: 4 }}>Day of week</Text>
          <Select
            style={{ width: 160 }}
            value={dayOfWeek}
            onChange={setDayOfWeek}
            options={WEEKDAY_OPTIONS}
          />
        </div>
        <div>
          <Text strong style={{ display: 'block', marginBottom: 4 }}>Time</Text>
          <TimePicker format="HH:mm" value={time} onChange={v => v && setTime(v)} />
        </div>
      </Space>
      <div style={{ marginTop: 16 }}>
        <Button
          type="primary"
          icon={saved ? <CheckCircleOutlined /> : <SaveOutlined />}
          loading={saving}
          onClick={save}
        >
          Save Schedule
        </Button>
      </div>
    </Card>
  );
}

// ── Snapshot history — same list as the Weekly Report page's own dropdown,
// with delete added (not available there, since that page is open to any
// viewer, not just admins).
function SnapshotHistoryCard() {
  const { message } = App.useApp();
  const [snapshots, setSnapshots] = useState([]);
  const [loading, setLoading] = useState(true);
  const [deletingId, setDeletingId] = useState(null);

  const load = () => {
    setLoading(true);
    api.get('/weekly-report/snapshots')
      .then(r => setSnapshots(r.data || []))
      .catch(() => message.error('Failed to load snapshot history'))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []); // eslint-disable-line

  const remove = async (id) => {
    setDeletingId(id);
    try {
      await api.delete(`/weekly-report/snapshots/${id}`);
      message.success('Snapshot deleted');
      setSnapshots(prev => prev.filter(s => s.id !== id));
    } catch (e) {
      message.error(e.response?.data?.error || 'Failed to delete snapshot');
    } finally {
      setDeletingId(null);
    }
  };

  const columns = [
    { title: 'Report Date', dataIndex: 'report_date' },
    {
      title: 'Generated By',
      dataIndex: 'generated_by',
      render: v => <Tag color={v === 'scheduler' ? 'blue' : 'gold'}>{v === 'scheduler' ? 'Scheduler' : 'Manual'}</Tag>,
    },
    { title: 'Created At', dataIndex: 'created_at', render: v => new Date(v).toLocaleString() },
    {
      title: '',
      key: 'actions',
      width: 110,
      render: (_, row) => (
        <Space size={4}>
          <Link to={`/weekly-report?snapshot=${row.id}`}>
            <Button size="small" icon={<EyeOutlined />} title="View this snapshot" />
          </Link>
          <Popconfirm
            title="Delete this snapshot?"
            description="This cannot be undone."
            okText="Delete"
            okButtonProps={{ danger: true }}
            onConfirm={() => remove(row.id)}
          >
            <Button size="small" danger icon={<DeleteOutlined />} loading={deletingId === row.id} />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <Card className="dashcard">
      <Space style={{ marginBottom: 16 }}>
        <FileTextOutlined style={{ fontSize: 20, color: '#5a4fcf' }} />
        <Title level={5} style={{ margin: 0 }}>Snapshot History</Title>
      </Space>
      <Table
        rowKey="id"
        size="small"
        loading={loading}
        dataSource={snapshots}
        columns={columns}
        pagination={{ pageSize: 10, hideOnSinglePage: true }}
      />
    </Card>
  );
}

export default function WeeklyReportAdmin() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '24px 0' }}>
      <style>{DASH_CSS}</style>
      <Title level={4} style={{ margin: '0 0 4px' }}>Weekly Report Administration</Title>
      <Text type="secondary" style={{ display: 'block', marginBottom: 20 }}>
        Manage the automatic snapshot schedule and clean up past snapshots. Teams notifications and
        report content itself are managed from the Weekly Report page.
      </Text>
      <ScheduleCard />
      <SnapshotHistoryCard />
    </div>
  );
}
